#!/usr/bin/env python3
"""
Process Throttle-RPM Calibration Data

Analyzes throttle_rpm_calibration_[datetime].csv files generated by
throttle_rpm_mapping.py and creates an averaged calibration curve suitable
for replay operations.

Features:
- Averages RPM values across all ESCs
- Combines UP and DOWN directions to account for hysteresis
- Extrapolates to 100% throttle using linear fit from 35% to max measured point
- Outputs simplified CSV with throttle_percent and rpm_mean columns

Usage:
    python process_calibration.py input_calibration.csv [options]

Example:
    python process_calibration.py ./calibration_data/throttle_rpm_calibration_20240115_143022.csv
    python process_calibration.py ./calibration_data/throttle_rpm_calibration_20240115_143022.csv --output averaged_calibration.csv
"""

import argparse
import csv
import os
from datetime import datetime
import numpy as np


def parse_arguments():
    """Parse and validate command-line arguments"""
    parser = argparse.ArgumentParser(
        description='Process throttle-RPM calibration data',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )

    parser.add_argument(
        'input_file',
        type=str,
        help='Path to input throttle_rpm_calibration CSV file'
    )

    parser.add_argument(
        '--output',
        type=str,
        default=None,
        help='Output file path (default: input_dir/throttle_rpm_mapping.csv)'
    )

    parser.add_argument(
        '--extrapolate-from',
        type=float,
        default=35.0,
        help='Starting throttle percentage for extrapolation slope calculation'
    )

    parser.add_argument(
        '--extrapolate-to',
        type=float,
        default=100.0,
        help='Target throttle percentage for extrapolation'
    )

    args = parser.parse_args()

    # Validation
    if not os.path.exists(args.input_file):
        parser.error(f"Input file not found: {args.input_file}")

    if args.extrapolate_from < 0 or args.extrapolate_from > 100:
        parser.error("extrapolate-from must be between 0 and 100")

    if args.extrapolate_to < 0 or args.extrapolate_to > 100:
        parser.error("extrapolate-to must be between 0 and 100")

    if args.extrapolate_to <= args.extrapolate_from:
        parser.error("extrapolate-to must be greater than extrapolate-from")

    return args


def load_calibration_csv(filepath):
    """
    Load and parse calibration CSV file

    Returns:
        dict: Parsed calibration data with structure:
            {
                'metadata': {dict of header comments},
                'data': [list of row dicts],
                'esc_ids': [list of ESC IDs found]
            }
    """
    print(f"Loading calibration file: {filepath}")

    metadata = {}

    with open(filepath, 'r') as f:
        # Parse metadata from header comments
        for line in f:
            line = line.strip()
            if not line.startswith('#'):
                break

            # Parse metadata lines like "# ESCs: 4"
            if ':' in line:
                parts = line[1:].split(':', 1)
                key = parts[0].strip()
                value = parts[1].strip()
                metadata[key] = value

        # Reset to beginning and skip comments
        f.seek(0)
        reader = csv.DictReader(line for line in f if not line.startswith('#'))
        rows = list(reader)

    if len(rows) == 0:
        raise ValueError("CSV file is empty")

    # Identify ESC columns
    esc_ids = []
    for col in rows[0].keys():
        if col.endswith('_rpm_mean'):
            esc_id = col.replace('_rpm_mean', '')
            esc_ids.append(esc_id)

    print(f"  Found {len(esc_ids)} ESCs: {', '.join(esc_ids)}")
    print(f"  Loaded {len(rows)} data rows")

    return {
        'metadata': metadata,
        'data': rows,
        'esc_ids': esc_ids
    }


def compute_averaged_calibration(calibration_data, extrapolate_from, extrapolate_to):
    """
    Compute averaged calibration curve across all ESCs

    Steps:
    1. For each throttle point, average RPM across all ESCs
    2. Average UP and DOWN directions for each throttle point
    3. Extrapolate to target throttle using linear fit

    Returns:
        dict: {
            'throttle': np.array of throttle percentages,
            'rpm': np.array of averaged RPM values
        }
    """
    print("\nProcessing calibration data...")

    rows = calibration_data['data']
    esc_ids = calibration_data['esc_ids']

    # Step 1: Aggregate data by throttle point and direction
    # Structure: {throttle: {'UP': [rpms], 'DOWN': [rpms]}}
    throttle_data = {}

    for row in rows:
        throttle = float(row['throttle_percent'])
        direction = row['direction']

        if throttle not in throttle_data:
            throttle_data[throttle] = {'UP': [], 'DOWN': []}

        # Collect RPM values from all ESCs
        rpms = []
        for esc_id in esc_ids:
            rpm_col = f'{esc_id}_rpm_mean'
            if rpm_col in row:
                rpm = float(row[rpm_col])
                rpms.append(rpm)

        # Average across ESCs for this throttle/direction
        if rpms:
            avg_rpm = np.mean(rpms)
            throttle_data[throttle][direction].append(avg_rpm)

    # Step 2: Average UP and DOWN directions for each throttle point
    throttles = []
    rpms = []

    for throttle in sorted(throttle_data.keys()):
        all_rpms = throttle_data[throttle]['UP'] + throttle_data[throttle]['DOWN']

        if all_rpms:
            avg_rpm = np.mean(all_rpms)
            throttles.append(throttle)
            rpms.append(avg_rpm)

    throttles = np.array(throttles)
    rpms = np.array(rpms)

    print(f"  Measured throttle range: {throttles[0]:.1f}% to {throttles[-1]:.1f}%")
    print(f"  Measured RPM range: {rpms[0]:.1f} to {rpms[-1]:.1f}")

    # Step 3: Extrapolate to target throttle
    if extrapolate_to > throttles[-1]:
        print(f"\nExtrapolating to {extrapolate_to}% throttle...")

        # Find points >= extrapolate_from for slope calculation
        mask = throttles >= extrapolate_from

        if np.sum(mask) < 2:
            print(f"  ⚠ Warning: Not enough points >= {extrapolate_from}% for extrapolation")
            print(f"  Using all available points instead")
            fit_throttles = throttles
            fit_rpms = rpms
        else:
            fit_throttles = throttles[mask]
            fit_rpms = rpms[mask]

        # Linear fit: RPM = slope * throttle + intercept
        coeffs = np.polyfit(fit_throttles, fit_rpms, deg=1)
        slope = coeffs[0]
        intercept = coeffs[1]

        print(f"  Linear fit using {len(fit_throttles)} points from {fit_throttles[0]:.1f}% to {fit_throttles[-1]:.1f}%")
        print(f"  Slope: {slope:.2f} RPM per % throttle")
        print(f"  Intercept: {intercept:.2f} RPM")

        # Calculate extrapolated RPM
        extrapolated_rpm = slope * extrapolate_to + intercept
        print(f"  Extrapolated RPM at {extrapolate_to}%: {extrapolated_rpm:.1f}")

        # Append extrapolated point
        throttles = np.append(throttles, extrapolate_to)
        rpms = np.append(rpms, extrapolated_rpm)

    print(f"\nFinal calibration curve: {len(throttles)} points")
    print(f"  Throttle range: {throttles[0]:.1f}% to {throttles[-1]:.1f}%")
    print(f"  RPM range: {rpms[0]:.1f} to {rpms[-1]:.1f}")

    return {
        'throttle': throttles,
        'rpm': rpms
    }


def save_averaged_calibration(calibration_curve, output_path, original_metadata):
    """
    Save averaged calibration curve to CSV

    Output format:
        # Averaged Throttle-RPM Calibration
        # Original file: [metadata]
        # Processing date: [timestamp]
        #
        throttle_percent,rpm_mean
        0.0,0.0
        5.0,1234.5
        ...
    """

    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)

    with open(output_path, 'w', newline='') as f:
        # Write header comments
        f.write("# Averaged Throttle-RPM Calibration\n")
        f.write(f"# Processing date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")

        if original_metadata:
            f.write("#\n# Original file metadata:\n")
            for key, value in original_metadata.items():
                f.write(f"#   {key}: {value}\n")

        f.write("#\n")

        # Write CSV data
        writer = csv.writer(f)
        writer.writerow(['throttle_percent', 'rpm_mean'])

        for throttle, rpm in zip(calibration_curve['throttle'], calibration_curve['rpm']):
            writer.writerow([f'{throttle:.1f}', f'{rpm:.1f}'])



def main():
    """Main execution function"""
    args = parse_arguments()

    # Load input CSV
    calibration_data = load_calibration_csv(args.input_file)

    # Compute averaged calibration curve
    calibration_curve = compute_averaged_calibration(
        calibration_data,
        args.extrapolate_from,
        args.extrapolate_to
    )

    # Determine output path
    if args.output is None:
        input_dir = os.path.dirname(args.input_file) or './calibration_data'
        output_path = os.path.join(input_dir, f"throttle_rpm_mapping.csv")
    else:
        output_path = args.output

    # Save results
    save_averaged_calibration(
        calibration_curve,
        output_path,
        calibration_data['metadata']
    )


if __name__ == "__main__":
    main()